---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(network)
library(igraph)
```

```{r}
data <- read.csv("/Users/shiwei/Desktop/研究论文/一带一路回音室/edgelist_matrix_副本.csv")
data_attr <- read.csv("/Users/shiwei/Desktop/研究论文/一带一路回音室/单个用户情感及流行度得分.csv")
```


```{r}
# 转换成边列表（邻接名单）的形式，as.matrix()在这里还是起到了转换成可以处理的邻接名单形式
data_matrix <- as.matrix(data)
head(data_matrix)
```

# 使用network包
```{r}
data_network <- as.network(data_matrix, directed = TRUE, multiple = F) # 转换成网络时，保留边的权重：multiple = TRUE
data_network
```


```{r}
# 下面的代码就是把属性添加到节点上
data_network %v% 'compound' <- data_attr$compound
data_network %v% 'sumpopular' <- data_attr$sumpopular
data_network
```


```{r}
# 获取邻接矩阵
adjacency <- as.matrix(data_network)

# 转换为igraph的网络对象
data_ig_network <- graph_from_adjacency_matrix(adjacency)
```



```{r}
# 获取节点属性
nodes <- data_attr$username # 定义节点属性列表
attributes <- data_attr$compound # 定义节点属性值列表

# 使用V()函数过滤节点属性列表
nodes <- nodes[nodes %in% V(data_ig_network)]
attributes <- attributes[nodes %in% V(data_ig_network)]
g_new <- igraph(data_ig_network)
# 设置节点属性
for (i in seq_along(nodes)) {
  set.vertex.attribute(g_new, nodes[i], "age", attributes[i])
}
```

```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

